license="${mod_license}"
issueTrackerURL="https://github.com/winnetrie83/SimpleStages/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/winnetrie83/SimpleStages"
authors="Winnetrie"
description='''
A lightweight NeoForge progression mod with an in-game stage editor for recipes, items, blocks, dimensions, mobs and structures. Built for modpacks and servers without requiring stage datapacks.
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
